apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-8cle
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-8cle
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-8cle
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-8cle
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-8cle
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-pmzi-tenant/rhtap-demo-app/hacbs-test-project-8cle@sha256:e20e7a771d716fc7fbb6b3483b97903f9fba185151464f4e9db26310ce8c2fdd
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
